// ──────────────────────────────────────────────
// EduPay — PDF Receipt Generator (Stage 8)
// ──────────────────────────────────────────────
// Generates a styled PDF receipt for a processed payment and uploads
// it to Firebase Storage. Returns the public URL.
//
// IMPORTANT: This file uses .tsx because @react-pdf/renderer requires
// JSX for its <Document>, <Page>, <Text>, <View> components.

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from '@react-pdf/renderer';
import { uploadPdfToCloudinary } from './cloudinary';
import type { Payment, Student, Invoice, School } from '@/types';
import { kobotoNaira } from './constants';

/**
 * Generate a PDF receipt for a processed payment, upload to Firebase Storage,
 * and return the public URL.
 */
/**
 * Render the PDF receipt to a Buffer.
 */
export async function generateReceiptPdfBuffer(
  payment: Payment,
  student: Student,
  invoice: Invoice,
  school: School
): Promise<Buffer> {
  const receiptNumber = `RCP-${payment.id.slice(0, 8).toUpperCase()}`;
  const dateStr = payment.processedAt ?? payment.createdAt;

  const doc = (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* School Header */}
        <Text style={styles.header}>{school.name}</Text>
        <Text style={styles.subheader}>
          Payment Receipt — {receiptNumber}
        </Text>
        <Text style={styles.date}>Date: {dateStr}</Text>

        {/* Divider */}
        <View style={styles.divider} />

        {/* Student Info */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Student Details</Text>
          <Text style={styles.field}>
            Student: {student.fullName}
          </Text>
          <Text style={styles.field}>Class: {student.class}</Text>
          <Text style={styles.field}>
            Admission No: {student.admissionNumber}
          </Text>
          <Text style={styles.field}>
            Virtual Account: {student.virtualAccountNumber}
          </Text>
          {payment.transactionReference && (
            <Text style={styles.field}>
              Transaction Ref: {payment.transactionReference}
            </Text>
          )}
        </View>

        {/* Allocation Breakdown */}
        {payment.allocations.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Allocation Breakdown</Text>
            {/* Table Header */}
            <View style={styles.tableHeaderRow}>
              <Text style={styles.tableHeaderLeft}>Description</Text>
              <Text style={styles.tableHeaderRight}>Amount</Text>
            </View>
            {/* Table Rows */}
            {payment.allocations.map((a, index) => (
              <View key={index} style={styles.row}>
                <Text style={styles.rowLeft}>{a.description}</Text>
                <Text style={styles.rowRight}>
                  {kobotoNaira(a.amountAllocated)}
                </Text>
              </View>
            ))}
          </View>
        )}

        {/* Summary */}
        <View style={styles.divider} />
        <View style={styles.section}>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Amount Received:</Text>
            <Text style={styles.summaryValue}>
              {kobotoNaira(payment.amount)}
            </Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Outstanding Balance:</Text>
            <Text style={styles.summaryValue}>
              {kobotoNaira(invoice.outstandingBalance)}
            </Text>
          </View>
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by {school.name} Financial Reconciliation System
        </Text>
      </Page>
    </Document>
  );

  const pdfStreamBuffer = await renderToBuffer(doc);
  return Buffer.from(pdfStreamBuffer);
}

/**
 * Generate a PDF receipt for a processed payment, upload to Cloudinary (if configured),
 * or fallback to local receipt URL.
 */
export async function generateReceipt(
  payment: Payment,
  student: Student,
  invoice: Invoice,
  school: School
): Promise<string> {
  const localFallbackUrl = `/api/receipts/${payment.id}`;

  try {
    const buffer = await generateReceiptPdfBuffer(payment, student, invoice, school);

    const publicId = `receipts/${student.schoolId}/${student.id}/${payment.id}`;
    const secureUrl = await uploadPdfToCloudinary(buffer, publicId);

    // If secureUrl is the Cloudinary placeholder domain, we prefer our local fallback URL
    if (secureUrl.includes('placeholder-cloud') || !secureUrl) {
      console.warn(
        '[receipt-generator] Cloudinary upload failed, falling back to on-demand generation: ' +
          'Cloudinary is not configured or returned a placeholder URL.'
      );
      return localFallbackUrl;
    }

    return secureUrl;
  } catch (err) {
    console.warn(
      '[receipt-generator] Cloudinary upload failed, falling back to on-demand generation: ' +
        (err instanceof Error ? err.message : String(err))
    );
    return localFallbackUrl;
  }
}

// ── PDF Styles ──────────────────────────────

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: 'Helvetica',
    color: '#1e293b',
  },
  header: {
    fontSize: 20,
    fontWeight: 700,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 4,
    color: '#0f172a',
  },
  subheader: {
    fontSize: 14,
    marginBottom: 6,
    color: '#475569',
    fontFamily: 'Helvetica-Bold',
  },
  date: {
    fontSize: 10,
    color: '#64748b',
    marginBottom: 8,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    marginVertical: 12,
  },
  section: {
    marginTop: 8,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 8,
    color: '#334155',
  },
  field: {
    fontSize: 11,
    marginBottom: 3,
    color: '#475569',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#cbd5e1',
    paddingBottom: 4,
    marginBottom: 4,
  },
  tableHeaderLeft: {
    fontWeight: 700,
    fontFamily: 'Helvetica-Bold',
    fontSize: 10,
    color: '#334155',
  },
  tableHeaderRight: {
    fontWeight: 700,
    fontFamily: 'Helvetica-Bold',
    fontSize: 10,
    color: '#334155',
    textAlign: 'right',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 3,
    paddingVertical: 2,
  },
  rowLeft: {
    fontSize: 11,
    color: '#475569',
  },
  rowRight: {
    fontSize: 11,
    color: '#1e293b',
    textAlign: 'right',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  summaryLabel: {
    fontSize: 12,
    fontWeight: 700,
    fontFamily: 'Helvetica-Bold',
    color: '#334155',
  },
  summaryValue: {
    fontSize: 12,
    fontWeight: 700,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 9,
    color: '#94a3b8',
    textAlign: 'center',
  },
});
